# Generated by Django 3.2.6 on 2021-08-21 07:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='voter',
            field=models.ManyToManyField(related_name='voter_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
